name: Build Claudia blog
on:
  push:
    branches: [ main ]
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0 # Specify pnpm version 10.8.0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0' # Specify Node.js version 23.11.0
          cache: 'pnpm'
      - run: pnpm install -g hexo-cli
      - run: pnpm install --frozen-lockfile
      - run: hexo generate
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          CLEAN: true
          BRANCH: gh-pages
          FOLDER: public/